### PR TITLE
Make Command::shouldShowStatus available in C and Swift

### PR DESCRIPTION
**Pull request by hartbit**
Can someone help me understand how to build `llbuildSwift` with CMake? I know I can built `llbuildSwift` with SwiftPM, but it isn't working currently because of the recent changes to version.h

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
I use:
`cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=Debug -DLLBUILD_SUPPORT_BINDINGS:=Swift ..`

**Comment by aciidb0mb3r** [comment]
We can never too many build systems!

**Comment by hartbit** [comment]
Ok, I got it building, if someone wants to review :-)

**Comment by hartbit** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
This seems reasonable, although we might want to eventually remove this logic from the core and make it all managed by the client

**Pull request merged**
