### PR TITLE
Finalize all sql statements when database gets closed

### PR DESCRIPTION
**Pull request by BenchR267**
Without finalizing the sqlite database doesn't get closed accordingly.

rdar://55274300

### CODE REVIEW

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
I don't see a way to actually test for that because there is not method for checking if there're still not finalized prepared statements.
But `sqlite3_close` returns `SQLITE_BUSY` if resources are not closed, finalized, finished accordingly. I added an assert for that since it's a development error and a test which opens and closes a connection and should hit this assert if that happens again.

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
That’s exactly what I had in mind, thanks!

**Comment by ddunbar** [comment]
@BenchR267 actually, just noticed: the close shouldn’t be inside the assert, no assert builds will not close the DB! Can you fix?

**Comment by BenchR267** [comment]
Oh true! Yes, I'll fix

**Pull request merged**
