### PR TITLE
Revert "Move C API versioning into Version.xcconfig"

### PR DESCRIPTION
**Pull request by atrick**
Reverts apple/swift-llbuild#239

### CODE REVIEW

**Comment by atrick** [comment]
@swift-ci smoke test.

**Comment by atrick** [comment]
@dmbryson @ddunbar Can one of you please merge this revert PR, or checkin the fix ASAP?

rdar://38417076

**Comment by ddunbar** [comment]
Sure

**Comment by ddunbar** [comment]
Done

**Comment by atrick** [comment]
@ddunbar Thanks!

**Pull request merged**
