### PR TITLE
Update manifest version to 5.0

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This allows us to use the latest build settings API for linking the
required libraries.

### CODE REVIEW

**Comment by ddunbar** [comment]
My only concern here is that this will break things for older users. Should we add a compatibility manifest for them, and leave the entries in the module map for now?

**Comment by aciidb0mb3r** [comment]
I was thinking about that but I don't know if it's worth it.

**Comment by jakepetroules** [comment]
Why are you not using `systemLibrary` targets for this?

**Comment by aciidb0mb3r** [comment]
for what?

**Comment by jakepetroules** [comment]
For linking sqlite and curses.

**Comment by aciidb0mb3r** [comment]
system library targets are required when you want to expose a system library to Swift but in this case we just need to link them.

**Comment by jakepetroules** [comment]
@aciidb0mb3r You can merge this now.

**Comment by dmbryson** [comment]
Concerns of breaking things were founded.  Some downstream projects have experienced build failures.  Going to revert for now.

**Pull request merged**
