### PR TITLE
Propose fix a typo

### PR DESCRIPTION
**Pull request by jeis2497052**
OK to fix two typos ?  OK to remove some trailing white space ?

### CODE REVIEW

**Comment by ddunbar** [comment]
Thanks for the contribution!

Typos yes, but please don't change trailing whitespace in areas of the document you don't modify (just makes PR review / blame more annoying).

**Comment by jeis2497052** [comment]
sorry about the trailing space.  I can kill this PR then no problem.

**Comment by ddunbar** [comment]
Well I'd still like the typo fixes! :)

**Comment by jeis2497052** [comment]
OK, I will try one more time.  I have emacs configured to automatically remove trailing spaces as my default config.

**Pull request closed without merging**
