### PR TITLE
[build] use Python3 to run lit

### PR DESCRIPTION
**Pull request by edymtt**
Address rdar://75786134

### CODE REVIEW

**Comment by edymtt** [comment]
@swift-ci please smoke test

**Comment by edymtt** [comment]
Confirmed tests are using python3

```
15:05:44 [0/1][  0%][0.000s] cd /Users/buildnode/jenkins/workspace/swift-llbuild-PR-macos-smoke-test/buildbot_incremental/llbuild-macosx-x86_64/tests && /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 /Users/buildnode/jenkins/workspace/swift-llbuild-PR-macos-smoke-test/llvm-project/llvm/utils/lit/lit.py -sv --param build_mode=Release /Users/buildnode/jenkins/workspace/swift-llbuild-PR-macos-smoke-test/buildbot_incremental/llbuild-macosx-x86_64/tests
```

**Comment by edymtt** [comment]
Also tests in Linux presets are using Python3

```
15:23:56 [0/1][  0%][0.000s] cd /home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux-smoke-test/build/buildbot_incremental/llbuild-linux-x86_64/tests && /usr/bin/python3.5 /home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux-smoke-test/llvm-project/llvm/utils/lit/lit.py -sv --param build_mode=Release /home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux-smoke-test/build/buildbot_incremental/llbuild-linux-x86_64/tests
```

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by edymtt** [comment]
@swift-ci please smoke test macOS

**Comment by edymtt** [comment]
@swift-ci please smoke test macOS

**Comment by edymtt** [comment]
@swift-ci please smoke test Linux

**Comment by edymtt** [comment]
@swift-ci please smoke test macOS

**Review by jakepetroules — APPROVED** [review]

**Pull request merged**
