### PR TITLE
Add and use platform abstractions for popen and pclose

### PR DESCRIPTION
**Pull request by hughbe**
Also clang-format PlatformUtility.h

### CODE REVIEW

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@hughbe for some reason your access didn't land across all repos, you should have access now if you want to try here?

**Comment by hughbe** [comment]
Looks like it's working now - thanks

**Pull request merged**
