### PR TITLE
Replace calls to sprintf with snprintf for safety

### PR DESCRIPTION
**Pull request by jakepetroules**
rdar://88514140

### CODE REVIEW

**Review by BenchR267 — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Review by dmbryson — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci please smoke test macOS

**Comment by shahmishal** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
