### PR TITLE
Introduce and use PlatformUtility.unlink

### PR DESCRIPTION
**Pull request by hughbe**
Avoids #ifdefs and unavoidable unistd.h imports on windows

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test and merge

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
Looks related:
```
FAILED: : && /usr/bin/clang++   -std=c++14 -fno-rtti -fno-exceptions -Wmost -Wdocumentation  -Woverloaded-virtual -Wparentheses -Wswitch -Wunused-function -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wsign-compare -Wnewline-eof -Wdeprecated-declarations -Winvalid-offsetof -Wnon-virtual-dtor -fPIC -include "/home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux/llbuild/include/libstdc++14-workaround.h" -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -g  -fuse-ld=gold unittests/Core/CMakeFiles/CoreTests.dir/BuildEngineTest.cpp.o unittests/Core/CMakeFiles/CoreTests.dir/DependencyInfoParserTest.cpp.o unittests/Core/CMakeFiles/CoreTests.dir/DepsBuildEngineTest.cpp.o unittests/Core/CMakeFiles/CoreTests.dir/MakefileDepsParserTest.cpp.o  -o unittests/Core/CoreTests  -rdynamic lib/libgtest.a lib/libgtest_main.a lib/libllbuildCore.a lib/libllvmSupport.a -lsqlite3 -lcurses lib/libgtest.a -lpthread -ldl && :
/home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux/llbuild/lib/Core/SQLiteBuildDB.cpp:105: error: undefined reference to 'llbuild::basic::sys::unlink(char const*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by ddunbar** [comment]
@hughbe can you check the failure here?

**Comment by hughbe** [comment]
Sorry for the delay! I've investigated the build failures - it was to do with the fact that CoreTests links llbuildCore, but not llbuildBasic, resulting in undefined symbol errrors. I couldn't repro on my machine, but now that I've got the tests compiling, everything seems to work

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please test Linux Platform

**Comment by ddunbar** [comment]
Great, LGMT once tests pass.

**Pull request merged**
