### PR TITLE
Basic tracing support

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please smoke test OS X

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test OS X

**Comment by ddunbar** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
