### PR TITLE
Add backstop value for DEVELOPER_INSTALL_DIR build setting

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Review by aciidb0mb3r — APPROVED** [review]

**Comment by jakepetroules** [comment]
please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@dmbryson Can you force merge this if CI fails again? An unrelated Ninja test is failing, which has nothing to do with this.

**Pull request merged**
