### PR TITLE
[CMake] Add dependency on the Swift compiler version

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
<rdar://problem/42543712> Rebuild Swift bindings when Swift compiler changes

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test

**Comment by jrose-apple** [comment]
Any reason to not just depend on the path to swiftc itself?

**Comment by aciidb0mb3r** [comment]
@jrose-apple path doesn't change on the CI

**Comment by jakepetroules** [comment]
> Any reason to not just depend on the path to swiftc itself?

In theory that's less reliable since the entirety of the compiler's implementation is not in the driver.

**Comment by aciidb0mb3r** [comment]
@jrose-apple I am not sure if that works as the Swift compiler is not an output of the build process. This is what we do for in llbuild for Swift packages. I guess we can remove this once we have ABI

**Comment by aciidb0mb3r** [comment]
https://github.com/apple/swift-llbuild/blob/master/lib/BuildSystem/BuildSystem.cpp#L2704

**Comment by jrose-apple** [comment]
This isn't about ABI stability; it's module stability.

**Comment by aciidb0mb3r** [comment]
2empag

**Comment by aciidb0mb3r** [comment]
I don't think so. The Xcode build system should take care of that.

**Pull request merged**
