### PR TITLE
[llbuildSwift] Add some convenience extensions for dealing with `BuildValueFileTimestamp`

### PR DESCRIPTION
**Pull request by akyrtzi**

### CODE REVIEW

**Comment by akyrtzi** [comment]
@swift-ci smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Review by jakepetroules — APPROVED** [review]

**Pull request merged**
