### PR TITLE
[CMake] Add necessary definitions for Windows SDK

### PR DESCRIPTION
**Pull request by hughbe**
We need this for various llvmSupport build fixes

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test OS X

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
Could you retrigger the tests for this - I don't imagine this would affect anything non-windows related!

**Comment by aciidb0mb3r** [comment]
@swift-ci please test linux

**Pull request merged**
