### PR TITLE
Move some install path settings into the xcconfig file

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Review by dmbryson — APPROVED** [review]

**Comment by dmbryson** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
