### PR TITLE
Fix Release build preprocessor definitions

### PR DESCRIPTION
**Pull request by dmbryson**

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Can you explain, I can’t tell the issue just from the diff

**Comment by dmbryson** [comment]
Ah, yes. Release.xcconfig sets GCC_PREPROCESSOR_DEFINITIONS to include $(COMMON_PREPROCESSOR_DEFINITIONS) and NDEBUG=1.  The project level and several targets were overriding these without also using $(inherited).   This change ensures that all targets are inheriting COMMON_PREPROCESSOR_DEFINITIONS as expected.

The bug caused by the lack of these definitions is that the PerfTest bot fails to build libllbuild.

**Comment by ddunbar** [comment]
Got it, thanks!

**Pull request merged**
