### PR TITLE
Remove a bunch of redundant settings from the project file

### PR DESCRIPTION
**Pull request by jakepetroules**
...and move a few key ones into xcconfig.

### CODE REVIEW

**Comment by jakepetroules** [comment]
We should probably move even more of them around, but let's start with these redundant ones which don't change any behavior.

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
FWIW, I checkout out and verified these changes locally.  We unfortunately still don't have automated CI on the Xcode project (its been requested, but still in queue).

**Pull request merged**
