### PR TITLE
Notify the delegate when the engine has become aware of a task's discovered dependencies

### PR DESCRIPTION
**Pull request by jakepetroules**
rdar://76129954

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Review by dmbryson — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test macOS

**Pull request merged**
