### PR TITLE
[CAPI] Fix DirectoryTreeSignature path call

### PR DESCRIPTION
**Pull request by dmbryson**
rdar://problem/45655532

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by owensd** [comment]
This looks good. Are there any other places this might pop up? =)

**Comment by dmbryson** [comment]
Heh, indeed there was another.

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test linux

**Comment by dmbryson** [comment]
@swift-ci please smoke test linux

**Comment by dmbryson** [comment]
Yeah, when I found this I was sad that there wasn't any test coverage and the thought had occurred to me.  So with the leading question, I've added at least coverage for the BuildSystemInvocation part.  The CAPI really could use tests...

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test linux

**Comment by dmbryson** [comment]
@swift-ci please smoke test linux

**Comment by dmbryson** [comment]
@swift-ci please smoke test linux

**Pull request merged**
