### PR TITLE
Revert "Allow concurrent scanning of dependencies for incremental builds"

### PR DESCRIPTION
**Pull request by johari**
This temporarily reverts https://github.com/apple/swift-llbuild/pull/832 and https://github.com/apple/swift-llbuild/pull/863 due to downstream test failures.

### CODE REVIEW

**Comment by johari** [comment]
@swift-ci please smoke test

**Review by jakepetroules — APPROVED** [review]
@erikolofsson Apologies, but we found some issues in some internal tests due to this change, and are reverting for now pending further investigation.

CC @dmbryson @aciidb0mb3r

**Comment by johari** [comment]
@swift-ci please smoke test

**Comment by johari** [comment]
@swift-ci please smoke test

**Pull request merged**
