### PR TITLE
Call `taskIsComplete()` on CommandTask cancellation

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Before this change, complete is only being called inside the command closure here: https://github.com/apple/swift-llbuild/blob/6a38f64e1b1a3419b0030ca2df6a4d8f72b0d3d3/lib/BuildSystem/BuildSystem.cpp#L546-L548 -- since that isn't run for cancelled commands, it will never complete.

**Comment by ddunbar** [comment]
But that will call `command.inputsAvailable(bsci, this)` which should also be responsible for calling taskIsComplete even if the operation is cancelled, right? I'm wondering if there is another case where we are missing the completion, basically.

**Comment by neonichu** [comment]
But the whole closure isn't called because we are not scheduling any further jobs after cancellation. I was wondering the same thing and will do a review of our other tasks to see if we are missing this in other places.

**Comment by neonichu** [comment]
Just to close the loop for our future selves: #104 and #105 should take care of this, because we no longer simply skip tasks when cancelling and rather make sure we don't do much actual work.

**Pull request merged**
