### PR TITLE
Fix llbuildSwift build on Windows

### PR DESCRIPTION
**Pull request by gmittert**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
Ugh. The OS X build keeps failing on all of these PRs because the host installed version of lit has a broken builtin 'cat'.  It should be possible to fix that by finding the lit that has been built/installed along with the rest of swift in the test workspace, I just haven't had the time to make the necessary changes.

**Comment by gmittert** [comment]
Rebased

@swift-ci please test

**Comment by gmittert** [comment]
@swift-ci please smoke test

**Comment by gmittert** [comment]
Closing in favor of #475

**Pull request closed without merging**
