### PR TITLE
build: add a dependency on the compiler

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Rather than depending on the version output, depend on the actual
compiler.

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test

**Comment by aciidb0mb3r** [comment]
Hm, this doesn't work properly either

**Comment by aciidb0mb3r** [comment]
@compnerd we might need to just go with python

**Comment by jakepetroules** [comment]
What part is not working? Do you have a build log?

**Comment by aciidb0mb3r** [comment]
cmake fails to rebuild when I change swiftc to point to a different compiler.

**Comment by gottesmm** [comment]
@aciidb0mb3r @compnerd What is the status of this? What are we waiting on?

**Comment by aciidb0mb3r** [comment]
This didn't work but we had already added back dependency on the compiler.

**Pull request closed without merging**
