### PR TITLE
Use `set` instead of `unordered_set`

### PR DESCRIPTION
**Pull request by neonichu**
Turns out that `std::set_difference` does not work with unordered sets, but this didn't become apparent with the smaller sets we are using in the unit tests.

> The elements in the ranges shall already be ordered according to this same criterion

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Can we also ensure we have test coverage of something which exposed the problem here? Maybe just a test case with more files?

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Pull request merged**
