### PR TITLE
Cleanup up generate version.h build phase

### PR DESCRIPTION
**Pull request by dmbryson**
Fix a typo in the output file declaration, add descriptive comment, and
have the script reference input/output file declarations directly.

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test os x

**Comment by shahmishal** [comment]
@swift-ci please smoke test os x

**Pull request merged**
