### PR TITLE
Fix the tests build

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test Linux

**Review by BenchR267 — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
@swift-ci please smoke test Linux

**Pull request merged**
