### PR TITLE
Fixed for Cygwin

### PR DESCRIPTION
**Pull request by tinysun212**
Cygwin doesn't have SIGUNUSED.

### CODE REVIEW

**Comment by ddunbar** [comment]
The SIGUNUSED comment doesn't seem relevant, since this was presumably trying to reset all signals and I guess that fails there too?

Does Cygwin really allow all signals to be set except SIGSTOP & SIGKILL?

**Comment by tinysun212** [comment]
Cygwin header doesn't define the SIGUNUSED, so the `sigaddset()` loop for Linux couldn't be used.

When I tried to reset all signals as like the case for `#else`, the `posix_spawn()`  didn't work.
After adding `sigdelset()` for the signals SIGSTOP & SIGKILL, llbuild worked well.

**Comment by ddunbar** [comment]
Ok, then lets just add that code to the main code path (used on Darwin)... they can't be masked, so there is no reason for trying even on OSes that allow it. This way we at least only have two paths.

**Comment by tinysun212** [comment]
Moved the code to the main path.

**Comment by ddunbar** [comment]
Thanks!

@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Pull request merged**
