### PR TITLE
[BuildSystem] Change lambda capture syntax for downstream CI failure

### PR DESCRIPTION
**Pull request by dmbryson**

### CODE REVIEW

**Comment by dmbryson** [comment]
Is there a way to run the full tests on a PR?

**Comment by dmbryson** [comment]
@swift-ci please test linux

**Comment by dmbryson** [comment]
Well, that did something...

**Comment by dmbryson** [comment]
@swift-ci please test ubuntu14.04

**Comment by aciidb0mb3r** [comment]
That will just run the full test suite of Swift. I don't think there is a way to test on ubuntu 14.04 from a PR. /cc @shahmishal

**Pull request closed without merging**
