### PR TITLE
Add file-system client config attribute support

### PR DESCRIPTION
**Pull request by dmbryson**
Allows setting 'device-agnostic' file system in the build file

rdar://problem/37445150

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Nice! Can you also update docs/build-system.md to document the new property?

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Pull request merged**
