### PR TITLE
Stale file removal fixes for Swift 4.0

### PR DESCRIPTION
**Pull request by neonichu**
These are cherry-picked commits from `master` for stale file removal fixes we want to take for Swift 4.0.

The changes are from the following PRs: #158, #167, #169, #170 and #175.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by rballard** [comment]
Approved for the swift 4 branch.

**Comment by neonichu** [comment]
Linux CI failure is unrelated, probably an incremental build issue.

**Comment by neonichu** [comment]
@swift-ci please smoke test linux

**Comment by ddunbar** [comment]
Foundation failed to build:
/home/buildnode/disk2/workspace/swift-llbuild-PR-Linux-smoke-test/Ninja-ReleaseAssert/foundation-linux-x86_64/TestFoundation/TestFoundation: symbol lookup error: /home/buildnode/disk2/workspace/swift-llbuild-PR-Linux-smoke-test/Ninja-ReleaseAssert/foundation-linux-x86_64/TestFoundation/TestFoundation: undefined symbol: _T06XCTest0A4CaseC12testRunClassyXlXpSgfg

@shahmishal can you clear the workspace?

**Comment by shahmishal** [comment]
@swift-ci Please clean smoke test Linux

**Pull request merged**
