### PR TITLE
test: replace `rm -rf ... && mkdir -p ...` with `%empty-directory`

### PR DESCRIPTION
**Pull request by compnerd**
This replicates the `%empty-directory` lit substitution from Swift into
the llbuild test configuration.  This is helpful as it ensures that the
operation is a single operation and is wired through lits internal
handling properly.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci smoke test os x

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with `main` branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
