### PR TITLE
Add API to configure dynamic CAPIExternalCommands

### PR DESCRIPTION
**Pull request by BenchR267**
Allows dynamically created CAPIExternalCommands to get configured using the
same key/values as in the manifest even if they get created during the build.
First usage is ExternalCommand in Swift specify discovered dependency file paths.

rdar://87706942

### CODE REVIEW

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Review by jakepetroules — APPROVED** [review]

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
@swift-ci please smoke test

**Pull request merged**
