### PR TITLE
<rdar://58458757> llbuild's gtest currently fails to build with SwiftPM

### PR DESCRIPTION
**Pull request by jakepetroules**
Thanks to @aciidb0mb3r for the patch.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
Clang modules are incomprehensible, "ok" I guess, although this hardly feels like the right fix. :/

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test osx

**Comment by jakepetroules** [comment]
@swift-ci please smoke test osx

**Comment by dmbryson** [comment]
@swift-ci please smoke test osx

**Comment by dmbryson** [comment]
@swift-ci please smoke test osx

**Comment by dmbryson** [comment]
@swift-ci please smoke test os x

**Comment by dmbryson** [comment]
@swift-ci please smoke test os x

**Pull request merged**
