### PR TITLE
More fixes for the tests build

### PR DESCRIPTION
**Pull request by jakepetroules**

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Review by BenchR267 — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci smoke test Linux

**Comment by shahmishal** [comment]
@swift-ci smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci smoke test macOS

**Comment by jakepetroules** [comment]
@swift-ci smoke test macOS

**Pull request merged**
