### PR TITLE
[BuildSystem] Fix bug where directory contents were always recomputed.

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@dduan, Could this be related to this PR? 
https://ci.swift.org//job/oss-swift-package-linux-ubuntu-16_04/530/consoleFull#-1082042515fca400bf-2f4a-462e-b517-e058d770b2d7
```

FAIL: llbuild-unit :: BuildSystem/BuildSystemTests/BuildSystemTaskTests.directorySignature (110 of 143)
******************** TEST 'llbuild-unit :: BuildSystem/BuildSystemTests/BuildSystemTaskTests.directorySignature' FAILED ********************
Note: Google Test filter = BuildSystemTaskTests.directorySignature
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BuildSystemTaskTests
[ RUN      ] BuildSystemTaskTests.directorySignature
/home/buildnode/disk2/workspace/oss-swift-package-linux-ubuntu-16_04/llbuild/unittests/BuildSystem/BuildSystemTaskTests.cpp:167: Failure
Value of: resultA->toData() != resultB->toData()
  Actual: false
Expected: true
[  FAILED  ] BuildSystemTaskTests.directorySignature (3 ms)
[----------] 1 test from BuildSystemTaskTests (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BuildSystemTaskTests.directorySignature

 1 FAILED TEST

********************
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 
Testing Time: 4.60s
********************
Failing Tests (1):
    llbuild-unit :: BuildSystem/BuildSystemTests/BuildSystemTaskTests.directorySignature

```

**Comment by ddunbar** [comment]
I'm not @dduan, but this does seem related, I will investigate.

 - Daniel

**Comment by ddunbar** [comment]
I believe this was eb70edac0bdf3d7fcb42e31165324bcbc851cef5 which exposed some problem on 16.04 -- I reverted in 480253fd26ac4f9b236ed4b621c64b711335916e and will investigate. Please let me know if you see it again (because I landed another patch which touched the area)

**Comment by shahmishal** [comment]
@ddunbar Sorry! Thanks for reverting the patch, I will let you know if I see this again.

**Pull request merged**
