### PR TITLE
Remove some unnecessarily ableist language.

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test macOS platform

**Comment by ddunbar** [comment]
@swift-ci please smoke test macOS platform

**Comment by dmbryson** [comment]
@swift-ci please smoke test os x

**Comment by dmbryson** [comment]
@swift-ci please smoke test os x

**Comment by dmbryson** [comment]
Given that these are just comment changes, I'm going to merge this to move on.

**Pull request merged**
