### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Review by dmbryson — APPROVED** [review]

**Comment by finagolfin** [comment]
@neonichu, why is this `llbuild` executable being built as a dependency here and in apple/swift-package-manager#6809 now? It just [broke my Android CI when cross-compiling trunk for armv7](https://github.com/finagolfin/swift-android-sdk/actions/runs/5973992300/job/16207329445#step:6:7130), which I can fix, but I wonder if you intend to build this executable or need the underlying libraries instead.

**Comment by neonichu** [comment]
Sorry about that, yes I meant `libllbuild`. I was using `--explicit-target-dependency-import-check`, it's possible that it gave me incorrect information which I did not verify sufficiently.

**Comment by neonichu** [comment]
Yah, indeed I am seeing 

```
[error]: Target llbuildAnalysis imports another target (llbuild) in the package without declaring it a dependency.
[error]: Target llbuildSwift imports another target (llbuild) in the package without declaring it a dependency.
```

**Comment by finagolfin** [comment]
I was able to work around this for trunk on my Android CI, finagolfin/swift-android-sdk#119.

**Comment by finagolfin** [comment]
@neonichu, should I submit pulls to revert this or do you plan to do it? Just let me know.

**Comment by neonichu** [comment]
@finagolfin sorry, I forgot about this - would be great if you could do it, thanks!

**Pull request merged**
