### PR TITLE
[Core] Remove escaped spaces if present in MakefileDepsParser

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Fixes https://bugs.swift.org/browse/SR-1468

I am not too sure about this fix

### CODE REVIEW

**Comment by ddunbar** [comment]
This was a bad API design on my part... it matches a pattern we use in Clang but it isn't worth the complexity here. What we should do is return the unescaped word along with `actOnRuleStart` and `actOnRuleDependency`.

A good start to that would be just to have a temporary `SmallString` in `parse()`, and teach `lexWord` to always accumulate the unescaped string, and then pass it to the callbacks.

We should still pass the raw pointers too, because they can be used for diagnostics by clients (since they are guaranteed to be pointers into the original source buffer, and can be used to derived line and column info).

**Comment by ddunbar** [comment]
Any update here?

**Comment by aciidb0mb3r** [comment]
@ddunbar updated

**Comment by ddunbar** [comment]
Landed a version of this patch here: 26206baf938d25fbb7b1778991fea745c1a530cb, which handles more escape characters correctly and uses StringRef at the API interface.

**Pull request closed without merging**
