### PR TITLE
Move C API versioning into Version.xcconfig

### PR DESCRIPTION
**Pull request by dmbryson**

### CODE REVIEW

**Comment by dmbryson** [comment]
This has the necessary fixes to the tests, but should wait for the builders to be updated to actually run said tests.

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test OS X

**Comment by dmbryson** [comment]
Confirmed that tests were run this time (and passed).

**Pull request merged**
