### PR TITLE
Strip ANSI colors unless CLICOLOR_FORCE is in effect

### PR DESCRIPTION
**Pull request by vlm**
rdar://51822760

### CODE REVIEW

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
The fix https://github.com/apple/swift-llbuild/pull/575/commits/aa08154e08ce4dd2c6ded783c2c4d5e4d38c43ab suggests that the CI uses `dash` for a shell (`/bin/sh`), since `dash` is strictly POSIX-compliant and can't use `\x1b` in the `echo` builtin.

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@ddunbar doesn't think like `printf` is any better [0]: POSIX doesn't let it use hexadecimals. In any case, the hex vs oct choice is not at all important in this patch.

 * [0] https://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html

**Pull request merged**
