### PR TITLE
Do Proper Shell Escaping on Windows

### PR DESCRIPTION
**Pull request by jmittert**
If the comments are too much/over the top, I can remove/reduce them. They were mostly there for my own benefit, but I left them in because exactly what it's doing is a bit cryptic otherwise.

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by jmittert** [comment]
Oh hold up, llvm has a function to quote args which does the same thing, I'll use that instead. However, it doesn't have one to escape the meta chars which we need if we're calling cmd.exe.

**Comment by jakepetroules** [comment]
Quoting for cmd.exe is different from quoting for CreateProcess, too. The former is much harder...

**Comment by jmittert** [comment]
Finally got around to fixing this. Also enhanced the tests somewhat.

This no longer applies metachar escaping, which is correct for CreateProcessW, but means when it prints out the commands, there are cases (if the command contains a `"`) where you wouldn't just be able to copy and past the command directly into cmd.exe and press enter. However, this means less visual clutter when printing it out and would still be fine for other shells with more sane quoting (e.g. powershell).

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Pull request merged**
