### PR TITLE
[Swift] Add build key types to BuildSystemBindings enum

### PR DESCRIPTION
**Pull request by dmbryson**
rdar://problem/46476230

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
Three different layers, sadly.  C++, C, and Swift.   Clearly we need to add some more language bindings...

**Comment by neonichu** [comment]
We just need Swift to work directly with C++, right :)

**Comment by dmbryson** [comment]
+1 to that

**Comment by jakepetroules** [comment]
Actually, there's a better way :)

PR coming...

**Pull request merged**
