### PR TITLE
Support command skipping with shouldCommandStart.

### PR DESCRIPTION
**Pull request by m-i-r-z-a**
This allows a build system delegate to run a subset of the build by
explicitly skipping commands yet allowing dependent commands to run.

### CODE REVIEW

**Comment by m-i-r-z-a** [comment]
@swift-ci please test

**Comment by m-i-r-z-a** [comment]
CI 404'd. @swift-ci please test

**Comment by m-i-r-z-a** [comment]
CI is back online. @swift-ci please test

**Comment by m-i-r-z-a** [comment]
A SwiftPM test failed:

/home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux/swiftpm/Tests/CommandsTests/PackageToolTests.swift:195: error: PackageToolTests.testPackageEditAndUnedit : XCTAssertEqual failed: ("5
") is not equal to ("8
") -

**Comment by m-i-r-z-a** [comment]
Looks like a non-deterministic test that @aciidb0mb3r is working on in b17929299accf4c40199dced7b9d977400190718 and c86035fb136f5a2e4ba2facb519932830d4e0026. Let's re-roll with those changes: @swift-ci please test

**Comment by m-i-r-z-a** [comment]
macOS CI hung in SwiftPM UtilityTests.ProgressBarTests testProgressBar. Ankit says it's a rare openpty bug that he's tracking. Going to need to restart it.

**Comment by m-i-r-z-a** [comment]
@shahmishal killed it. @swift-ci please test

**Comment by aciidb0mb3r** [comment]
Here is the openpty hang radar for reference
<rdar://problem/29898449> openpty sometimes blocks on reading master after closing slave

**Pull request merged**
