### PR TITLE
Syntactically normalize path names

### PR DESCRIPTION
**Pull request by vlm**
rdar://48965366

### CODE REVIEW

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Comment by vlm** [comment]
@swift-ci please smoke test

**Pull request merged**
