### PR TITLE
libllbuild: make the library static and internalise it

### PR DESCRIPTION
**Pull request by compnerd**
Convert libllbuild into static and avoid exporting the library for use in other projects.  The expected clients are only reliant on llbuildSwift.  This overall saves some space (~20K).  Additionally, it will simplify the redistribution in the toolchain by reducing the number of shared libraries while saving space.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
CC: @etcwilde @DougGregor

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by stevapple** [comment]
Ping here as merging https://github.com/apple/swift-llbuild/pull/859 alone is breaking the Windows build

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci test Windows

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Review by jakepetroules — APPROVED** [review]

**Pull request merged**
