### PR TITLE
build: migrate to CMake 3.15

### PR DESCRIPTION
**Pull request by compnerd**
Migrate to 3.15, use the CMake support for Swift content, use the export
targets for libdispatch and Foundation.  Remove the additional rules for
building the Swift content.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Woohoo! I think we'll need to wait until macOS nodes have 3.15 though. Also, I landed CMake 3.15 support for bootstrapping SwiftPM (just run `Utilities/new-bootstrap`). We should make sure this is compatible with that. In particular, we'll need to fix this at least: https://github.com/apple/swift-package-manager/blob/master/Sources/SPMLLBuild/CMakeLists.txt#L9-L24

**Comment by compnerd** [comment]
@aciidb0mb3r - my understanding is that the macOS builders should already have a compatible CMake.  You're right about the downstream usage - that code will just be replaced with a `find_package(llbuild CONFIG REQUIRED)`.  We now properly expose the Swift library as well, along with the necessary flag injection, so all we need to do is just link against it.

**Comment by aciidb0mb3r** [comment]
Hm, I thought they weren't updated yet. @shahmishal, can you confirm?

and yep, we already do find_package for llbuild (for getting the libllbuild target): https://github.com/apple/swift-package-manager/blob/master/CMakeLists.txt#L39

**Comment by compnerd** [comment]
Well, I suppose that settles that (from the macOS run):

```
14:53:00 CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
14:53:00   CMake 3.15.1 or higher is required.  You are running version 3.10.2
```

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27654

@swift-ci please smoke test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27654

@swift-ci please smoke test

**Comment by shahmishal** [comment]
We don’t have 3.15.1 cmake on macOS yet, I am planning on doing this next week.

**Comment by compnerd** [comment]
Been over a week, time to check!

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
@swift-ci please smoke test macOS

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#28151

@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
🎉

**Pull request merged**
