### PR TITLE
Add an option to ignore all but the first output when parsing make-style deps

### PR DESCRIPTION
**Pull request by owenv**
Some tools, like swiftc, produce make-style dependencies for multiple outputs where the inputs to each output are guaranteed to be identical. Allow configuring commands to short-circuit parsing for these tools as an optimization.

### CODE REVIEW

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Comment by owenv** [comment]
@swift-ci please test Windows platform

**Pull request merged**
