### PR TITLE
Fix MSVC warning building llbuild

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by ddunbar** [comment]
Is it possible to disable this MSVC warning for us, for now? If not, then I would rather find a way we can get the same warnings from Clang so that we all use a compatible warning set.

**Comment by ddunbar** [comment]
(we recently chose not to turn on signed conversion warnings for Clang, because I didn't feel it was actually an improvement to code quality to just do spot fixes like this)

**Comment by hughbe** [comment]
I think silencing them is the best idea, turns out we already did this in #57. I have reverted all my changes apart from turning `maximumLoadAverage` from a `float` to a `double`. This is because it is set by `::strtod`, so there is an actual risk of overflow here

**Comment by ddunbar** [comment]
Great!

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
I think the CI is down over christmas until 3rd Jan

**Comment by ddunbar** [comment]
@swift-ci please test

**Pull request merged**
