### PR TITLE
WIP: [SR-6053] Sketch minimal AF_UNIX based server.

### PR DESCRIPTION
**Pull request by ddunbar**
- This is mostly just the boilerplate around establishing a UNIX-domain socket
   connection between a client and server, there is no protocol definition, and
   the server implementation is lame.

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
We may revisit this as we consider expanding how build tools can integrate with llbuild, but for now we've got a more limited version of this in the LLBUILD_CONTROL_FD feature.  Going to close this PR out. The binary coding additions are separately in #376.

**Pull request closed without merging**
