### PR TITLE
Revert "[gtest] Remove recursive src/src symlink."

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
This reverts commit 5a1952763a2a8ba554e30ed61f425283680f6ddb.

Looks like removing this symlink broke SwiftPM support for gtest-related
targets.

### CODE REVIEW

**Comment by ddunbar** [comment]
Ugh. The recursive symlink was really gross, I'd like to look for a different workaround.

**Comment by ddunbar** [comment]
I prefer #364 can you confirm it works for you?

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
Yep, that works! Thanks!

**Pull request closed without merging**
