### PR TITLE
Do not crash if we get any sqlite errors in getKeyID().

### PR DESCRIPTION
**Pull request by neonichu**
See <rdar://problem/33897555>

I don't have a good idea on how to test this as we would need to lock the database at exactly the right time to hit this. We have some existing tests for similar errors already, though, so I think this should be fine.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@neonichu do you actually know what the error it is we are getting in this case?

**Comment by neonichu** [comment]
@ddunbar I couldn't reproduce this myself, but from what I understand from the reproduction case, it should be concurrent access to the sqlite database. In any case, the error message will forward the sqlite error message, so we could be getting more information from future reports.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Pull request merged**
