### PR TITLE
Add “archive” tool

### PR DESCRIPTION
**Pull request by mxcl**
Constructs an archive from provided inputs, intended for static library archives.

Takes `inputs` and `outputs` only.

Any virtual nodes are ignored when constructing the `ar` instantiation.

I consider this PR incomplete:

- [x] documentation (where to put it?)
- [x] using `inputs`/`outputs` as the only attributes seems inconsistent, so should I do something else?
- [x] `ArchiveShellCommand` probably is lacking some basic checks
- [x] should I add tests, if so, where?

So I await some feedback.

### CODE REVIEW

**Comment by ddunbar** [comment]
Documentation goes in `docs/buildsystem.rst` currently, check the other tools for precedent.

Tests go in `tests/BuildSystem/Build`, let me know if you have trouble running them. Check that dir for some examples of what kinds of stuff I usually check (typical is (a) initial build, (b) build with no change, (c) build with an incremental change).

Will do a more complete review ASAP, not sure yet about the inputs/outputs question.

**Comment by ddunbar** [comment]
After pondering on it a bit I'm fine with the current strategy of just deriving the inputs and outputs from the declared dependency edges. As the FIXME in the code notes I would probably add an error check (you can do this when the "Command" is run) that at least one output and one input exists.

We may eventually want to split these out, but I don't see a reason to overcomplicate it now and that is consistent with what "mkdir" and "symlink" are currently doing.

**Comment by mxcl** [comment]
Revised, please advise.

**Comment by ddunbar** [comment]
Can you make it so the change will still respect a `description` field, if set, and otherwise fall back to the default here? This is something I want clients to be able to have control over.

Also, can you squash?

**Comment by mxcl** [comment]
Done. Will squash, rebase and merge if you OK all the changes.

**Comment by ddunbar** [comment]
LGTM, thanks!!

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test

**Comment by mxcl** [comment]
@swift-ci Please test

**Pull request merged**
