### PR TITLE
convert findRuleResultStmt query to join for lookupRuleResult

### PR DESCRIPTION
**Pull request by aciidb0mb3r**

### CODE REVIEW

**Comment by aciidb0mb3r** [comment]
this is failing `llbuild :: Ninja/Build/tracing-scanning.ninja`
```
Command 8 Stderr:
/Users/aciid/mycode/swift.org/llbuild/tests/Ninja/Build/tracing-scanning.ninja:27:10: error: expected string not found in input
# CHECK: { "rule-scanning-next-input", "[[RULE2]]", "[[RULE3]]" },
         ^
/Users/aciid/mycode/swift.org/llbuild/build/tests/Ninja/Build/Output/tracing-scanning.ninja.tmp.trace-out:34:1: note: scanning from here
{ "readying-task-input-request", "T2", "R4" },
^
/Users/aciid/mycode/swift.org/llbuild/build/tests/Ninja/Build/Output/tracing-scanning.ninja.tmp.trace-out:34:1: note: with variable "RULE2" equal to "R4"
{ "readying-task-input-request", "T2", "R4" },
^
/Users/aciid/mycode/swift.org/llbuild/build/tests/Ninja/Build/Output/tracing-scanning.ninja.tmp.trace-out:34:1: note: uses undefined variable "RULE3"
{ "readying-task-input-request", "T2", "R4" },
^
/Users/aciid/mycode/swift.org/llbuild/build/tests/Ninja/Build/Output/tracing-scanning.ninja.tmp.trace-out:40:1: note: possible intended match here
{ "readied-task", "T2", "R2" },
^
```

```
$ cat /Users/aciid/mycode/swift.org/llbuild/build/tests/Ninja/Build/Output/tracing-scanning.ninja.tmp.trace-out                                                       
[
{ "build-started" },
{ "new-rule", "R1", "build.ninja" },
{ "handling-build-input-request", "R1" },
{ "checking-rule-needs-to-run", "R1" },
{ "rule-does-not-need-to-run", "R1" },
{ "build-ended" },
{ "build-started" },
{ "new-rule", "R2", "output" },
{ "handling-build-input-request", "R2" },
{ "checking-rule-needs-to-run", "R2" },
{ "rule-scheduled-for-scanning", "R2"},
{ "paused-input-request-for-rule-scan", "R2" },
{ "new-rule", "R3", "input-2" },
{ "checking-rule-needs-to-run", "R3" },
{ "rule-needs-to-run", "R3", "invalid-value" },
{ "rule-scanning-next-input", "R2", "R3" },
{ "new-task", "T1" },
{ "created-task-for-rule", "T1", "R3" },
{ "rule-scanning-deferred-on-task", "R2", "T1" },
{ "readied-task", "T1", "R3" },
{ "finished-task", "T1", "R3", "changed" },
{ "rule-scanning-next-input", "R2", "R3" },
{ "rule-needs-to-run", "R2", "input-rebuilt", "R3" },
{ "handling-build-input-request", "R2" },
{ "new-task", "T2" },
{ "created-task-for-rule", "T2", "R2" },
{ "handling-task-input-request", "T2", "R3" },
{ "readying-task-input-request", "T2", "R3" },
{ "new-rule", "R4", "input-1" },
{ "handling-task-input-request", "T2", "R4" },
{ "checking-rule-needs-to-run", "R4" },
{ "rule-does-not-need-to-run", "R4" },
{ "readying-task-input-request", "T2", "R4" },
{ "completed-task-input-request", "T2", "R4" },
{ "updated-task-wait-count", "T2", 1 },
{ "completed-task-input-request", "T2", "R3" },
{ "updated-task-wait-count", "T2", 0 },
{ "unblocked-task", "T2" },
{ "readied-task", "T2", "R2" },
{ "finished-task", "T2", "R2", "unchanged" },
{ "build-ended" },
]
```

**Comment by aciidb0mb3r** [comment]
looks like if I call `getOrInsertKey(rule.key);` in `lookupRuleResult` it passes

**Comment by aciidb0mb3r** [comment]
Fixed the broken test by changing the order of input, follow up bug: https://bugs.swift.org/browse/SR-1249

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by aciidb0mb3r** [comment]
@ddunbar I'd like to see the boy results when you have them

**Comment by ddunbar** [comment]
Results from this change versus previous:

screen shot 2016-04-16 at 7 19 10 pm

Full results from this change versus before either PR:
screen shot 2016-04-16 at 7 21 05 pm

My summary is: small net win on a few benchmarks, small regression on a more micro benchmarks (the no execute tests don't really track deps). Upshot for me is we get the win in database size, but probably need to rethink DB API to get all the performance wins I was hoping for here.

**Pull request merged**
