### PR TITLE
Fixed assertion checks in SQLiteBuildDB

### PR DESCRIPTION
**Pull request by BenchR267**
Used the correct number of expected columns for those SQL statements.

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by BenchR267** [comment]
I don't know but they clearly are wrong (comparing the statements vs the expectations).

**Comment by jakepetroules** [comment]
It's possible the `assert` is getting compiled out in our tests.

**Comment by BenchR267** [comment]
If the `assert`s get compiled out during development and in the tests it might not be useful to have them there 🙂 Should we use a different mechanism instead of assert?

**Comment by ddunbar** [comment]
They will be compiled out in release builds, but I assumed we had a debug builder somewhere.

@dmbryson can you check on this (and the PR)?

**Comment by dmbryson** [comment]
We do have a debug builder.  This particular method `void dump(raw_ostream& os)`, however, is not exercised in our tests.  (my fault, d'oh!)

The changes look good.  We probably _should_ have a test that exercises this code.  That said, it is only used for the command line db debug tool, so I wouldn't consider adding such coverage a blocker for this PR.

**Pull request merged**
