### PR TITLE
[Ninja] Fix a crash in the parser.

### PR DESCRIPTION
**Pull request by ddunbar**
- In certain cases, the lexer wouldn't be properly taken out of the customized
   lexing mode for particular errors.

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Comment by dmbryson** [comment]
@swift-ci please smoke tesf

**Comment by dmbryson** [comment]
@swift-ci please smoke test mac os

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by ddunbar** [comment]
@swift-ci please smoke test

**Pull request merged**
